### ISSUE TITLE
time() and gettimeofday() broken in v2

### ISSUE THREAD

**Issue by kakaroto** [HACKERCHANNEL/PSL1GHT#103]
time() and gettimeofday() both seem to be broken in the latest psl1ght. The previous version seemed to work fine and returned proper time() values, but the latest version always returns the same value.
If you want to test it, simply compile the cairo sample and you'll see "FPS : Inf" on the screen.. If you define DEBUG to printf, it should also print the time and the difftime between when the app was started and the current time (which returns 0.00).
The cairo sample is on my repo in the 'cairo' branch at https://github.com/kakaroto/PSL1GHT/tree/cairo

**Comment by kakaroto** [comment]
My cairo branch was merged into ps3dev repository, so you'll find the sample here instead of the first URL I put :
https://github.com/ps3dev/PSL1GHT/tree/master/samples/graphics/cairo

**Comment by shagkur** [comment]
gettod and settod added. those are the low level functions called by gettimeofday/settimeofday and time
