### ISSUE TITLE
PSL1GHT fails to auto install

### ISSUE THREAD

**Issue by morleyrj** [HACKERCHANNEL/PSL1GHT#105]
The Cygwin auto installtion process fails when installing the ps3libraries. The cause is due to zlib having been updated to version 1.2.7 from version 1.2.6. The file zlib-1.2.6.tar.gz therefore no longer exists (referenced from ps3 libraries tar ball) which stops the installation.

The update of the zlib files only took place on 2nd May and am sure you guys are on the case. Can you please advise when the ps3 libraries have been updated and I'll re-try the installation.

Many thanks!

**Comment by ooPo** [comment]
This should be fixed now, see: https://github.com/ps3dev/ps3libraries/pull/19

**Comment by morleyrj** [comment]
Dan,
 
Many thanks for letting me know.  I'll try a fresh install.
 
Best regards,
 
Roger
