### ISSUE TITLE
PS3Load feature request: transfer package data files

### ISSUE THREAD

**Issue by phire** [HACKERCHANNEL/PSL1GHT#15]
A pkg file can include as many data files as it likes, as well as extra self and prx files. But PS3Load can only load a single self. This means when start using extra files, running your program becomes a pain in the butt.

To make things nice and streamlined again, PS3Load should transfer any extra files that will get included in the final pkg file to the same temporary folder that the self will be launched from. To make things even faster, PS3Load should only transfer files that haven't already been transfered, maybe based on a checksum or just modification date.

**Comment by AerialX** [comment]
You can now transfer zip files, they will be extracted into tmp/ps3load and then any self or EBOOT.BIN found in the zip will be loaded. (If there are two .self files, it'll pick the one that appears last in the zip).

tmp/ps3load is cleared each time ps3load runs, so don't expect to use it to cache huge data files. An external drive is probably better for that anyway, but if you have some suggestions for improvements to this new system let me know.
