### ISSUE TITLE
Directory Iteration (dirent) Support

### ISSUE THREAD

**Issue by AerialX** [HACKERCHANNEL/PSL1GHT#17]
I'd implement all the dirent functions in libc-glue, but newlib doesn't install a valid dirent.h for us to use.

wat do?

**Comment by ooPo** [comment]
Newlib needs a proper ppu target where we can add things like this.

**Comment by Parlane** [comment]
How hard could dirent.h be? Can we just not implement it ourselves?

**Comment by AerialX** [comment]
Sure, writing it isn't the issue. The problem is where it goes.

Ideally we'd do what ooPo said, newlib needs some touching up for PPU anyway (for instance, ftruncate is ifdef'd out of unistd for some odd reason). That means coordinating some newlib patches.

I actually talked to shagkur the other day, who is doing some work on this for us. I probably should've mentioned that in the original description >.>

**Comment by Parlane** [comment]
Any news on this?

**Comment by ooPo** [comment]
A port of newlib was started (https://github.com/ooPo/newlib-1.18.0-PPU), with a target of ppu => powerpc64-unknown-lv2. The fun stuff is in newlib/libc/sys/lv2. I will give you access to this repository.

Currently most lv2 syscalls still exist in PSL1GHT, however zeldin added directory support 5 days ago. The patch in ps3toolchain is up to date and builds this version.

Ideally, I'd like to see all lv2 syscall-based code moved to newlib, while the sprx-based code stays in psl1ght.

**Comment by AerialX** [comment]
The recent merge has solved this.
