### ISSUE TITLE
32 bit opd entries.

### ISSUE THREAD

**Issue by phire** [HACKERCHANNEL/PSL1GHT#18]
The code we have at the moment to convert from a 64 bit opd to a 32 bit opd is a complete hack. 

Hermes [submitted an interesting patch](https://github.com/hermesEOL/PSL1GHT/commit/53e56fb837d), which modified sprxlinker to generate a 32bit opt entry that replaced the 64 bit null value after each 64 bit opt entry.

That means you could take the address of any function pointer and add 16 to get a valid 32 bit opd entry. 

I rejected it, because my quick look at the gcc source code had suggested that the null value could actually be 1 sometimes to mark the end of a list of function pointers. I didn't want some random piece of code that someone wrote in the future to fail because of this, because it would be really hard to debug.

A slightly better solution might be to generate a second .opd32 section, the conversion becomes:
    (opd_address - opd_base_address) >> 1 + opd32_base_address  
Which can probably be implemented as a macro or inline function.

Any thoughts? To me it seams the best solution short of modifying gcc, and if gcc does get modified in the future, we can replace the macro/inline function with something that does nothing and all our code will work fine.

**Comment by AerialX** [comment]
Just pushed a solution that creates a .opd32 section - sprxlinker populates it with a 32bit copy of .opd. Use the OPD32() macro from psl1ght/types.h to convert function pointers from now on.
