### ISSUE TITLE
PSL1GHT depends on closed source components to build

### ISSUE THREAD

**Issue by zeldin** [HACKERCHANNEL/PSL1GHT#36]
The PSL1GHT makefile now enforces building of vpcomp, which is dependent on
libCg, which is closed source and not available for all platforms.

Using an open-source alternative would be ideal, but failing that the Makefile
should at least exclude the vpcomp tool from the build if libCg is not available,
so that the more essential parts can still be built and installed.

**Comment by phire** [comment]
Yeah, I was planning to do this (the second part, not the first part) but nobody on irc at the time seemed to care.

**Comment by ooPo** [comment]
Any chance this is going to be done soon?

**Comment by Parlane** [comment]
Thankyou for fixing this ooPo.
