### ISSUE TITLE
shagkur's additions

### ISSUE THREAD

**Issue by ooPo** [HACKERCHANNEL/PSL1GHT#40]
When I build the shagkur branch of psl1ght, it generates self files that either lock up or reset the PS3 when executed with ps3load.

Is this branch considered unfinished? What is needed to finish these changes?

I don't mind fixing it myself, but it would be a lot nicer if there's a general list of what's missing.

**Comment by zeldin** [comment]
Well, to start off the list of things missing:  Only about half of the syscalls struct is filled.  Among the missing functions are the lwmutex ones.  Very bad.

**Comment by AerialX** [comment]
Old and merged.
