### ISSUE TITLE
Depth buffer needs to be 4 bytes wide

### ISSUE THREAD

**Issue by slicer4ever** [HACKERCHANNEL/PSL1GHT#41]
it seems unless the depth buffer is 4 bytes wide, people have problems with using the gpu for drawing, while it may work fine if writing directly to the framebuffer, it doesn't always work fine for using the rsx directly.

**Comment by phire** [comment]
Yeah, I noticed this, even if you aren't using the depth buffer you need to have a 32 bit depth buffer allocated.

It's a mystery, but I suspect that this is sony's fault, someone could check with the official SDK.

**Comment by slicer4ever** [comment]
ah, that actually explains alot, thanks for the info hermes
