### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#44]
Anyone know a sample to draw strings with colors that I can define the position?

**Comment by Jiboo** [comment]
http://cairographics.org/samples/

Just below arc and stroke (from cairo demo) :

```
cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
cairo_set_font_size(cr, 90.0);
cairo_move_to(cr, res.width/2, res.height/2);
cairo_show_text(cr, "Woot!");
```

**Comment by facferreira** [comment]
I know that and I am using it, but it is incompatible with PNG.

**Comment by Jiboo** [comment]
I don't really understand what you are trying to do. You want to draw a PNG on the screen using cairo? You can load a png on a cairo surface and apply it on the main surface.

**Comment by facferreira** [comment]
But I need to draw more than one png in the same surface...

**Comment by Jiboo** [comment]
http://cairographics.org/FAQ/#paint_from_a_surface
http://cairographics.org/manual/cairo-PNG-Support.html#cairo-image-surface-create-from-png (some stream helper to load png from memory would be a nice addition to the cairo port).

Just create one surface per png, and paint it on the main surface (https://github.com/HACKERCHANNEL/PSL1GHT/blob/master/samples/cairoTest/source/main.c#L105).
