### ISSUE TITLE
Feature Request - Fs support

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#49]
I just realized that the fs support (CELL_FS) is incomplete, it doesn't has support to see if a path is a file or a directory.

**Comment by Jiboo** [comment]
http://linux.die.net/man/2/stat

Does stat on path and S_ISDIR on st_mode work?

**Comment by facferreira** [comment]
I just checked out and realized that when it is a file it returns 2 and when it is a directory returns 1.
