### ISSUE TITLE
[Bug] Exiting From XMB

### ISSUE THREAD

**Issue by Parlane** [HACKERCHANNEL/PSL1GHT#5]
When using "Quit Game" from XMB menu, the PS3 is forcibly restarted which in turn deactivates the jailbreak and the ps3 must be restarted to be able to use anymore homebrew.

**Comment by phire** [comment]
Forcibly restarted? mine just locks up.

The homebrew app needs to register a callback with sysutilRegisterCallback. Its already in exports.h but it needs an wrapper function that adapts the callback to sony's weird 32bit pointer format.

**Comment by Parlane** [comment]
I have not seen that function used in the startup functions of a standard elf created with cell sdk and they have no problems.

**Comment by phire** [comment]
Its not a startup function, it is up to the developer to register that callback. You should find that every single sample app registers it in the main function. 

The same callback also tells you when the xmb menu is open, and you should really pause your game.

**Comment by Parlane** [comment]
Ah ok.

**Comment by phire** [comment]
This has been fixed, closing.
