### ISSUE TITLE
Python2 should be explicitly referenced

### ISSUE THREAD

**Issue by prg318** [HACKERCHANNEL/PSL1GHT#51]
Before making these changes, none of the sample programs would compile for me.  I'm using Arch Linux which defaults to python3, with python2 included (like many other modern distributions).  Python is a vital part of so many applications that simply removing python3 and making sure only python2 is installed isn't an option for many machines.

However, this workaround should work for everyone whether they have python3 installed or not.
in psl1ght/tools/PS3py/ there are three python scripts: sfo.py, pkg.py, and fself.py .  The first line of these scripts are #!/usr/bin/env python
This should be #!/usr/bin/env python2

python2 is a symlink to whatever version of python2 is installed.  this is what occurs by default, regardless of whether python3 is installed.  however, python could point to python2 or python3 depending on whether python3 is installed.

I also had issues with pkgcrypt.so.  Line #1 of crypt.c is #include<Python.py>  .  On my machine, this was including python3.1/Python.py but PSL1GHT requires the python2 version of this file.  I had to manually change it to #include<python2.7/Python.py> on my system.  It doesn't look like python symlinks a python2 directory in their installation, so I'm not sure how this one can be avoided without a macro or just having a note somewhere in the README that you may need to manually change this.

**Comment by prg318** [comment]
I know I probably could have done something with git to show the changes in the code, but they're simple enough for a bug report and i'm a git beginner anyway.

Hope to see the #!/usr/bin/env python lines changed by default at least!  There's no harm in doing this and it will only increase compatibility across machines.

**Comment by zeldin** [comment]
As a datapoint, my Ubuntu 10.10 system does _not_ have a symlink called "python2".  There is "python2.4" and "python2.6" however.  Seems to me that changing the shebang will just move the problem to other systems...

**Comment by prg318** [comment]
Interesting.  And changing to a "python2.x" would be no good; if you reference python2.6, a system with 2.7 will spout an error..

**Comment by AerialX** [comment]
Agreed, I use Arch and this has been annoying me for ages. I wasn't sure if python2 was installed by default on all distributions, and I guess it's not as zeldin says. I could write our own bash script that discovers the proper python version to use, but that doesn't solve the #include problem (which, by the way, I've never had a problem with).

**Comment by prg318** [comment]
distros should be providing a python2 symlink anyway

and besides its really simple to add  ln -s /usr/bin/python2.x /usr/bin/python2

if the code is python2 specific, it should really be calling python2

why not just port the code to python3?  python3 is available on most distros and afaik only a couple lines of code don't work properly on python3

**Comment by zeldin** [comment]
If the code could be modified so that it works on both python 2 and 3, that would probably be the best.  Then calling python would work on all systems (except those with only python 1 :).  What does the code use exactly that doesn't work in python 3?

**Comment by prg318** [comment]
There are some minor syntax things that you can see with the the 2to3 tool.  For one, """stuff""" should be ("""stuff""") for python3 compatibility.

The big thing that didn't work in python3 is the file writing calls.  I had to change all of the out.write(s) calls to out.write(s.encode('ascii')) or else python would complain about TypeErrors.

Python2 and python3 aren't made to be compatible.  My vote would be to change env to python2.  If the user gets bugs about no python2 , they can then make the symlink to python2.x (we can't predict what minor version the user will have, the distro should provide the python2 link)

i could even get make pkg for the samples to work with python3 mostly due to this error: 

Traceback (most recent call last):
  File "/home/lukas/ps3dev/PSL1GHT/psl1ght/build/bin/pkg.py", line 229, in <module>
    import pkgcrypt
ImportError: dynamic module does not define init function (PyInit_pkgcrypt)

This is an error having to do with the crypt.c file.  Apparently the module for writing c modules has changed from python2 to python3, but I'm not sure what PyInit function it requires.

**Comment by zeldin** [comment]
If python3 isn't meant to be compatible, then python shouldn't be a symlink to python3, and all code which is meant to use python 3 should call python3 instead of python.  Your suggestion to break compatibility and tell those who complain how to fix it does not make sense; we can already tell those who have problems with the _current_ setup (which are probably fewer; I hadn't even _heard_ about "Arch Linux" before today) how to fix them, so it wouldn't be an improvement over the current situation (except for _you_ personally).

**Comment by prg318** [comment]
::sigh:: /usr/bin/env python2 is the standard for python2 specific scripts.  Most distros (and I'm not only referring to Arch) include this python2 symlink (or are at least supposed to)

Referring to python2 is hardly "breaking compatibility".  If the shell complains about a missing python2 file, it's complaining for good reason since it should be there.

python can be symlinked to the default python on the machine (could be 1.x, 2.x, 3.x, no way to tell).  if a python2 symlink is not found, it should be created

other projects have had this same issue: http://lists.mcs.anl.gov/pipermail/petsc-dev/2010-October/003655.html

**Comment by zeldin** [comment]
I'm not talking about "should", I'm talking about reality.  The scripts now work out of the box on Ubuntu.  If you change them to use "python2" instead, they will not.  So you break compatibility with Ubuntu, which is a major distribution.  One can argue at length about whether Ubuntu or Arch is "right" or "wrong", but it's pointless to do so here.  The fact is that now the scripts work without manual intervention on Ubuntu but not on Arch.  If you change python to python2, you will just reverse this:  The scripts would work without manual intervention on Arch but not on Ubuntu.  That's not really fixing the problem, just moving it around.  If it's impossible to write scripts that work in both python2 and python3 (which sounds really odd), then some kind of configure script to find out the path for a pyhton2 interpreter would be needed to actually fix the problem.

**Comment by prg318** [comment]
You could easily write a configure script to symlink python2 to python2.x

There's really no point of maintaining a py2 and py3 version

**Comment by zeldin** [comment]
${PSL1GHT}/bin doesn't really seem like the right place for a "python2" symlink though.  Why not just use sed to modify the shebang of the scripts to contain the correct interpreter name?  I don't think the scripts are ever run from the source directory, so this could be done when installing them.

**Comment by zeldin** [comment]
I've pushed a branch python-detect to zeldin/PSL1GHT which replaces "python" in the shebang during install.  It's by no means perfect (it only tries a few hardcoded names, and doesn't actually check the version), but it should at least be an improvement over the status quo in that it will work both on a system where "python2" is python 2 and "python" is something else, and on a system where "python2" does not exist but "python" is python 2.  Feel free to try it out.

**Comment by prg318** [comment]
I'll check it out; i'm new to git so I'll have to figure out how to check out separate branches first

**Comment by zeldin** [comment]
First you need to add my repo as a remote:
`git remote add zeldin git://github.com/zeldin/PSL1GHT.git`

Then you can fetch all my branches with `git fetch zeldin`

Finally, to check out my "python-detect" branch, do
`git checkout zeldin/python-detect`
Note that you will not be able to commit to a remote branch, so you need to make your own branch from it to do any modifications.

**Comment by zeldin** [comment]
The latest commit to my branch (2650862) also tries to fix the compilation of pkgcrypt.so.  If the python2 installation isn't broken, running the setup script with python2 should ensure the correct include path.

**Comment by zeldin** [comment]
The fix seems to have been merged to master now, so I guess this issue can be closed?

**Comment by AerialX** [comment]
Yup :)
