### ISSUE TITLE
Make selfs and packages work on non-homebrew firmware

### ISSUE THREAD

**Issue by olsner** [HACKERCHANNEL/PSL1GHT#53]
It would be nice to have pkg files that can be run on none-homebrew:ed firmwares.

Likely dependent on someone to release a makeself program capable of creating the right kind of self files, and a corresponding packaging program, but once such a thing appears it would be nice to have it integrated in the pslight build system.

**Comment by Parlane** [comment]
Geohot has done some work on this, unsure where it is going and if it will be released.
