### ISSUE TITLE
Simplify integration of geohot's tools

### ISSUE THREAD

**Issue by hrydgard** [HACKERCHANNEL/PSL1GHT#54]
For now, one has to do the following in each makefile:
- The FSELF step in pkg:  needs to be replaced with make_self_npdrm. remove -n and add $(CONTENTID) as a third parameter
- Add a call to package_finalize after the @$(PKG) --contentid ... line

It would be nice if these steps were at least centralized in Makefile.base, so one doesn't have to make these modifications for each sample.

**Comment by AerialX** [comment]
Project makefile improvements. Closed by 95f2428abecac032ed28d2e8d1577814a29a1d84 #62 #63
