### ISSUE TITLE
libelf location on OS X

### ISSUE THREAD

**Issue by asgeir** [HACKERCHANNEL/PSL1GHT#61]
For MacPorts users on OS X the following CFLAGS and LDFLAGS need to be added

CFLAGS += -I/opt/local/include
LDFLAGS += -L/opt/local/lib

**Comment by SquidMan** [comment]
Users should probably do this on their own, by prefixing those to the make line.
As in:
CFLAGS=-I/opt/local/include LDFLAGS=-L/opt/local/lib make
If the Makefile doesn't support this, then that must be changed.

**Comment by ooPo** [comment]
I don't see why this can't be added to the default makefile.

**Comment by AerialX** [comment]
True, they should. We can't support every possible setup.

However, no harm in adding it. Done.
