### ISSUE TITLE
C++ Linking Files

### ISSUE THREAD

**Issue by naruse** [HACKERCHANNEL/PSL1GHT#62]
we should add to the makefiles of the SDK:

LD := $(CXX)

So when compiling C++ stuff the linker links! :)

**Comment by AerialX** [comment]
Well, only when $(CXXFILES) isn't empty.

**Comment by Parlane** [comment]
This does not work correctly for c only programs... or does it?

**Comment by naruse** [comment]
works correctly for C programs;at least the examples worked and some stuff I tested before moving it to C++ worked.

**Comment by AerialX** [comment]
Project makefile improvements. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f.
