### ISSUE TITLE
Move reusable pkg: commands to Makefile.base

### ISSUE THREAD

**Issue by Core-F** [HACKERCHANNEL/PSL1GHT#63]
If possible, please move the commands to make a package to makefile.base since they are same for every package made. It should be possible to import these with the makefile.base and fill in variables local to makefile.

Thx

**Comment by AerialX** [comment]
Project makefile improvements. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f. Closed by 66e7c1626ab3133b5c2e876fe25290b5d9fa6f0f.
