### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#68]
While trying to compile the latest version, when compiling for lv2-psl1ght.o it gives me many errors with file "dirent.c" namely with DIR.

**Comment by AerialX** [comment]
You need to install the new ps3toolchain for psl1ght to compile.

**Comment by facferreira** [comment]
Ok thanks, right now I am installing the latest ps3toolchain.

**Comment by facferreira** [comment]
I installed the new ps3toolchain and then tried to install psl1ght and same errors.

**Comment by AerialX** [comment]
You know we can't do anything unless you paste said errors, right?

**Comment by facferreira** [comment]
Here are two photos with the errors:
http://yfrog.com/h0qhsp
http://yfrog.com/h7gs0lp

**Comment by AerialX** [comment]
Just as I said, you're not using the new ps3toolchain. Uninstall any toolchain you may have now and use this: https://github.com/ooPo/ps3toolchain

**Comment by facferreira** [comment]
I did it, I removed my previous ps3toolchain and I tried to install the newest.

**Comment by AerialX** [comment]
Nope, you're quite obviously not using the new ps3toolchain there. Besides, the new ps3toolchain automatically builds and installs psl1ght for you.

**Comment by facferreira** [comment]
Maybe I forgot to remove anything from previous ps3toolchain. Thanks.
