### ISSUE TITLE
make install does not work

### ISSUE THREAD

**Issue by zeldin** [HACKERCHANNEL/PSL1GHT#75]
<pre><code>cp: cannot stat `extlib/libCg.so': No such file or directory
make[2]: *** [install] Error 1</code></pre>

Like with vpcomp, if proprietary binary-only stuff is not present, PSL1GHT should install without them.

**Comment by shagkur** [comment]
The main idea was to have the shared objects for the 3 major platforms in the git repository as well. But unfortunately git doesn't allow one to upload .so. From the license point of view, regarding the nvidia cg toolkit, we're allowed to redistribute them.
Else i admit that there's a need to install the compiler without the library if not present.

**Comment by zeldin** [comment]
Well, I'm not on any of your "3 major platforms", so adding the .so to the repo wouldn't help.  :-)

Looks like ooPo did a fix, but alas it will need to be reworked now that cgcomp can work without the lib (yes, totally my own fault...)

**Comment by shagkur** [comment]
well, that's unfortune ;) j/k.
Normally the .so or whatever is only needed when cgcomp is started due to late linking. Within the sources there shouldn't be any referrence (i.e. include) from the cg toolkit. So compiling should be fine. And i assume this worked for you? Also, after your change with the -a option and not using the cg tookit in this option should at least make cgcomp work, right?

**Comment by shagkur** [comment]
so what's left is just a correction of "make install" if the toolkit isn't present or can't be installed.

**Comment by zeldin** [comment]
Yup, that's what I meant.  With my changes I can run cgcomp just fine on my platform, as long as I use -a.  So the correct behaviour of the Makefiles should be to always build and install cgcomp, but only install the .so if it exists (and is compatible with the host architecture, but as long as you have to download the .so manually that's mostly a non-issue).

**Comment by shagkur** [comment]
Okay. i will take a look at it and fix this issue. the current solution, ooPo added, is kinda unlucky. only respects the *nix targets.

**Comment by shagkur** [comment]
i removed the complete extlib stuff from the Makefile and added a more informative message when loading of the cg lib fails.
