### ISSUE TITLE
missing 3 dot symbols in libpsl1ght.a

### ISSUE THREAD

**Issue by tdjb** [HACKERCHANNEL/PSL1GHT#78]
I rebuilt ooPo's ps3toolchain tonight followed by SDL_PSL1GHT.
Now I get following error when linking to SDL_PSL1GHT:

ppu-gcc -o game game.o netdll.so engine.o cache1d.o sdl_driver.o unix_compat.o a.o pragmas.o -B/home/tdjb/src/ps3dev/ps3toolchain/psl1ght/target/lib -B/home/tdjb/src/ps3dev/ps3toolchain/host/ppu/lib /home/tdjb/src/ps3dev/ps3toolchain/host/ppu/ppu/lib/lv2-psl1ght.o -lpsl1ght -llv2 -lSDL -lreality -lgcm_sys -lsysutil -lio -lc -lm -llv2 -lpsl1ght -laudio
/home/tdjb/src/ps3dev/ps3toolchain/psl1ght/target/lib/libSDL.a(SDL_systhread.o): In function `RunThread':
/home/tdjb/src/ps3dev/ps3toolchain/SDL_PSL1GHT/src/thread/psl1ght/SDL_systhread.c:65: undefined reference to`.sys_ppu_thread_exit'
/home/tdjb/src/ps3dev/ps3toolchain/psl1ght/target/lib/libSDL.a(SDL_systhread.o): In function `SDL_ThreadID':
/home/tdjb/src/ps3dev/ps3toolchain/SDL_PSL1GHT/src/thread/psl1ght/SDL_systhread.c:99: undefined reference to`.sys_ppu_thread_get_id'
/home/tdjb/src/ps3dev/ps3toolchain/psl1ght/target/lib/libpsl1ght.a(thread.o): In function `sys_ppu_thread_create':
/home/tdjb/src/ps3dev/ps3toolchain/build/psl1ght/libpsl1ght/source/thread.c:10: undefined reference to`.sys_ppu_thread_create_ex'

I looked at 'nm libpsl1ght.a' and found there are no dot-symbols which point to the definitions in liblv2.a

**Comment by AerialX** [comment]
You have "-llv2 -lpsl1ght" in your link line, get rid of it. It's already there earlier and that's the wrong order.

**Comment by tdjb** [comment]
Thank you AerialX!
I found out what my problem was. I should have taken a look at base.mk first how linking is done right before posting this issue.
