### ISSUE TITLE
Keyboard on screen

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#85]
I know it supports it fully, but I tried to adapt cellframework OSKUtil.cpp code to PSL1GHT, it compiles very well but doesn't work at all, may you provide a sample?

**Comment by Parlane** [comment]
Closing comment due to being a duplicate of #83

**Comment by facferreira** [comment]
Ok, I just hope that appear one answer for that issue. Thanks.
