### ISSUE TITLE
Pad controls

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#86]
I'm trying to use completely the pad but I'm having problems, I do not know how to use the analog right (R3) for direction down... May you help me? I would prefer in a similar way as it is here: https://github.com/HACKERCHANNEL/PSL1GHT/blob/master/include/io/pad.h Thanks.

**Comment by Parlane** [comment]
What do you mean? Why can't you use it?

**Comment by Parlane** [comment]
It is BTN_R3

**Comment by facferreira** [comment]
That is for pressure, I want when an user moves analog right to down.

**Comment by Parlane** [comment]
Unless you are talking about:

unsigned int ANA_R_H : 16;
unsigned int ANA_R_V : 16;

In that case you need to process the data yourself.

**Comment by facferreira** [comment]
How can I do it?

**Comment by Parlane** [comment]
Look at ANA_R_V, that will give a a value between 0 and 255 (inclusive). 0 being all the way at the top, and 255 being all the way at the bottom. If you check that ANA_R_V is > 200 it should count as down.

**Comment by Parlane** [comment]
P.S. R3 has no pressure sensitive data.

**Comment by facferreira** [comment]
Ok but then I have for example change 16 to 200? unsigned int ANA_R_V       : 200;

**Comment by Parlane** [comment]
What? No. Don't touch pad.h. That just defines the amount of bits.

**Comment by facferreira** [comment]
Ah ok.

**Comment by Parlane** [comment]
Have you played around with any pad tests etc?

**Comment by facferreira** [comment]
No.

**Comment by Parlane** [comment]
Maybe you should do that?

**Comment by facferreira** [comment]
How would you suggest me to do it in the better way?

**Comment by Parlane** [comment]
Do you know how to code?

**Comment by facferreira** [comment]
Yes.

**Comment by Parlane** [comment]
Then just code an example? Or look at the pad test sample ?

**Comment by facferreira** [comment]
Ok thanks.
