### ISSUE TITLE
script error 011-psl1ght.sh

### ISSUE THREAD

**Issue by tachion** [HACKERCHANNEL/PSL1GHT#95]
I'm getting this error while on the last stages of the script:

sed: 1: "s\$PSL1GHT\\n": substitute pattern can not be delimited by newline or backslash
make: **\* [install-rules] Error 1

any thoughts?

**Comment by tachion** [comment]
btw here is the code on that script for reference:

install-rules:
    @mkdir -p $(PSL1GHT)/host
    @cp rules/base.mk rules/ppu.mk rules/spu.mk $(PSL1GHT)/host/
    @ln -sf $(PSL1GHT)/host/ppu.mk $(PSL1GHT)/Makefile.base
    @mkdir -p $(PS3DEV)/host/ppu/ppu/lib
    @#cp rules/lv2.ld $(PS3DEV)/host/ppu/ppu/lib/
    @sed -e 's\$$PSL1GHT\$(PSL1GHT)\' -e 's\$$PS3DEV\$(PS3DEV)\' rules/lv2.ld > $(PS3DEV)/host/ppu/ppu/lib/lv2.ld

**Comment by ooPo** [comment]
Can you tell me your specific OS and version? This worked fine for me on Ubuntu 10.04.

**Comment by tachion** [comment]
I'm using MacOSX 10.6.6.  I followed the instructions found here: http://psl1ght.net/wiki/TutorialInstall:OSX

I used MacPorts, if that helps.

**Comment by tachion** [comment]
oh wait, I just got something from sed's man pages in mac:

BUGS
     Multibyte characters containing a byte with value 0x5C (ASCII `\') may be incorrectly treated as line continuation characters in arguments to the``a'',
``c'' and``i'' commands.  Multibyte characters cannot be used as delimiters with the``s'' and``y'' commands.

I don't use sed so I'm kinda lost on how to re-write that one line :(

**Comment by ooPo** [comment]
try changing the slashes from \ to /:

sed -e 's/$$PSL1GHT/$(PSL1GHT)/' -e 's/$$PS3DEV/$(PS3DEV)/' rules/lv2.ld > $(PS3DEV)/host/ppu/ppu/lib/lv2.ld

Does that work for you?

**Comment by ooPo** [comment]
I've reverted the sed line back to what was used before. You should be able to build now.

**Comment by tachion** [comment]
i'm compiling it right now.  i'll post the results in a few mins. 

btw, the line in 003-jpeg-8b.sh (/usr/src/ps3toolchain/build/ps3libraries/scripts) that downloads jpegsrc.v8b.tar.gz doesn't exist anymore.  I had to change that line to somewhere else (http://www.imagemagick.org/download/delegates/jpegsrc.v8b.tar.gz) just to make the script happy :)

**Comment by tachion** [comment]
Hi ooPo!

everything built ok.  thanks for the help :)

**Comment by tachion** [comment]
Hi ooPo!

everything built ok.  thanks for the help :)

**Comment by zeldin** [comment]
Well well well, I did say using \ for a delimiter was probably a bad idea, didn't I?  :-9
https://github.com/HACKERCHANNEL/PSL1GHT/pull/92#r6917

I still find it rather hard to believe that mingw make would have some kind of problem with the character ;. which is usually the one of choice when neither / or : can be used...
