### ISSUE TITLE
PSL1GHT-V2

### ISSUE THREAD

**Issue by ooPo** [HACKERCHANNEL/PSL1GHT#98]
It appears we have a growing split and need to discuss some things:

1) Are shagkur's V2 changes something we want to add?
2) If so, should we merge or jump directly to the new branch?

I'm all for adding new features with as minimal disruption as possible, but in this case the ongoing split may mean a quick transition is needed to avoid further division.

Take a look at the changes here: https://github.com/shagkur/psl1ght-v2

Thoughts?

**Comment by AerialX** [comment]
I'm for merging, while at the same time taking the chance to rearrange the PSL1GHT tree much like shagkur's. Not a direct jump though, there's too much drift and personally I'd like to make sure we take the time to merge the best from both. I've kinda started doing this locally.

I'd like to see some opinions on libreality vs. librsx.

**Comment by zerkman** [comment]
Beware psl1ght-v2 has switched to git-hacks.

http://git-hacks.com/devkitpro-addons/devkitps3-psl1ght-v2

I also would like all the stuff to be merged into a single project.

zerkman

**Comment by ooPo** [comment]
I also take issue with including precompiled code, especially if we don't have permission to do so.

**Comment by zerkman** [comment]
Most of the precompiled code is the Cg shared library which can anyway be retreived from nvidia-cg-toolkit (at the price of downloading a full toolkit while only the shared lib is required). There also is a win32-compiled version of socat.

Concerning librsx, it has working samples. It also features a heap manager which allows allocation AND deallocation of blocks in RSX memory. To me it is very usable. I have not much experience with libreality, mostly due to the lack of working samples.

**Comment by ooPo** [comment]
If their license requires a user to download and install the nvidia-cg-toolkit instead of distributing it ourselves, then that's what we have to do.

**Comment by ooPo** [comment]
I've merged the changes into V1 on my fork:
https://github.com/ooPo/PSL1GHT

Take a look if you're interested. I'd like to get this out of the way sooner rather than later. We need a list of what needs to be changed, added, or removed to make this something we can endorse.

1) Remove Cg.
2) Re-add the readme, authors and license files.
3) ...?

**Comment by ooPo** [comment]
If you want to easily test it, my fork of ps3toolchain will build V2 and a V2-compatible ps3libraries. Read the readme to set the environment properly beforehand.

**Comment by zerkman** [comment]
3) Get rid of the static environment variables prerequisites. The user should be able to install all psl1ght in a chosen directory, just like any library. Then it's his problem to deal with nonstandard installation directories and path environment. My opinion is to handle a configure script with autoconf / automake, which takes /usr/local as default prefix. This will provide a unified and portable way of configuring psl1ght on linux i386/linux amd64/linux ppc/mingw32/cygwin.
This will also handle the generation of cgcomp, depending on the presence of libCg or not.
4) Document all library calls and data structures in the doxygen doc, at least the higher level ones.I started documenting spu and rsx stuff.

The latest version of my documentation changes are in my git-hacks tree : http://git-hacks.com/~zerkman/devkitpro-addons/zerkmans-devkitps3-psl1ght-v2
A generated version of the doc in html format is here : https://zerkman.sector1.fr/ps3/psl1ght-v2/ . See Files/Globals for the list of documented calls and types.

**Comment by zerkman** [comment]
I have tested your ps3toolchain and psl1ght-v2 merge. I cloned both your repositories :
https://github.com/fgalea/ps3toolchain
https://github.com/fgalea/PSL1GHT

Concerning that ps3toolchain, I made minor dependency fixes.

Concerning PSL1GHT, I re-enabled cgcomp and removed all references to an included libCg. cgcomp compiles and installs, but fails to run if no libCg is present in the system. I also fixed minor execution right problems.

I guess we can say 1) is solved. I'm still working on 4) on my git-hacks clone of psl1ght-v2.

**Comment by zerkman** [comment]
5) re-enable "make pkg". Not sure we can "safely" sign selfs and pkg's, so unsigned stuff will be ok.

**Comment by ooPo** [comment]
This is good work. I've pulled the changes into my fork.

**Comment by ooPo** [comment]
1) Remove Cg.
- Done.

2) Re-add the readme, authors and license files.
- Done.

3) Get rid of the static environment variables prerequisites.
- Done.

4) Document all library calls and data structures in the doxygen doc
- Started, merged from the git-hacks repository.

5) re-enable "make pkg".
- Todo?

**Comment by zerkman** [comment]
Well done !

I'm still working on 4), which will take a long time to finish. I suppose we don't have to make that merge official as soon as possible.

**Comment by ooPo** [comment]
If nobody objects, I'd like to make this live by the end of the weekend.

One last thing: Do we leave it under HACKERCHANNEL/PSL1GHT, or move it to ps3dev/PSL1GHT?

**Comment by ooPo** [comment]
This was done!
